export const GET_TODOS = "todo/get"
export const ADD_TODO = "todo/add"
export const UPDATE_TODO = "todo/update"
export const DELETE_TODO = "todo/delete"
export const CLEAR_COMPLETED_TODO = "todo/clear_completed"